### PR TITLE
Make semicolons optional

### LINKED ISSUE #2: Everything breaks without semicolons
Should semicolons be optional? I'm not sure, but if not, it needs to be more clear that EVERY COMMAND MUST BE ENDED BY A SEMICOLON.

### PR DESCRIPTION
**Pull request by towerofnix**
Well, that was easy.

Fixes #2.

### CODE REVIEW

**Comment by bates64** [comment]
:D

**Comment by towerofnix** [comment]
Just gonna test w/ strings.

**Comment by 109C** [comment]
Made sure all the tests worked, I hope?

**Comment by towerofnix** [comment]
> Made sure all the tests worked, I hope?

Time to make those..

**Comment by bates64** [comment]
**use http://chaijs.com/** @liam4

**Comment by towerofnix** [comment]
Alright ~~everything~~ strings and command separators work

**Pull request merged**
