### PR TITLE
Add command line and MODULES!

### PR DESCRIPTION
**Pull request by bates64**
`tulun examples/filesystem.tul`

```
# use the fs module #
fs => use('fs');

# write to filesystem-test.txt #
fs.write('filesystem-test.txt', 'Hello there!');

# read filesystem-test.txt and print #
print('Contents of filesystem-test.txt:', fs.read('filesystem-test.txt'));
```

### CODE REVIEW

**Comment by towerofnix** [comment]
Suppose I want to have multiple copies of `tulun` installed -- how would I do that?

**Comment by bates64** [comment]
Multiple? See the `npm` docs - but you can also run `tulun` w/o `-g` with `./tulun` :package:

**Comment by towerofnix** [comment]
Ah okay as long as `./tulun` still works :P

**Comment by towerofnix** [comment]
How much of this was implemented into 0.1.0/0.1.1? I can more or less (#20) use `tulun` from the command line now.

**Comment by bates64** [comment]
I'll merge the rest of it myself @liam4, it's fine ;)

**Pull request closed without merging**
