### PR TITLE
String escapes

### PR DESCRIPTION
**Pull request by towerofnix**
Here are the self-descriptive tests:

```
> print('single quoted \'escape');
single quoted 'escape
> print("double quoted \"escape");
double quoted "escape
> print('newline\nescape');
newline
escape
> print('escape \\escape');
escape \escape
```

And here's the related grammar:

```
EscapeCode -> "\\" (. | "\n") {% function(d) { return d[1][0]; } %}
```

### CODE REVIEW

**Comment by towerofnix** [comment]
> hound — 47 violations found.

Oops! 

It's searching through `dist`..

**Comment by 109C** [comment]
Remove bot.

**Comment by towerofnix** [comment]
> Remove bot.

No kidding!

---

EDIT: Done.
EDIT2: Deleted its comments :P

**Comment by bates64** [comment]
Make a .houndignore file!

**Comment by bates64** [comment]
Uh, why do you have to double escape things? Surely `\\"` should become _\"_?

**Comment by towerofnix** [comment]
Oops.

I copied from the tests.js file!

Silly me.

**Comment by bates64** [comment]
Side note - it might be worth adding character escape colouring to strings in **tulun.tmLanguage**.

**Pull request merged**
