### PR TITLE
add optional `else` arg to `if()`

### PR DESCRIPTION
**Pull request by bates64**
```
# `if` can now take an `else` callback - just like `ifel` #
if(true, fn() {
    print("Called for true");
}, fn() {
    print("Called for false");
});
```

### CODE REVIEW

**Comment by towerofnix** [comment]
This is kind of nice :P

@kvackkvack @BookOwl please input here 📦

**Comment by BookOwl** [comment]
I like it.

**Comment by plastpappa** [comment]
Eh, I liked ifel better to be honest, but everybody else seems to be enjoying it, so I don't mind. :P

**Comment by bates64** [comment]
@kvackkvack*\* anyway, does it matter if you preferred `ifel`? Having **the option** yet still allowing both works better, right? :package:

**Comment by towerofnix** [comment]
Sounds great to me, everybody. Merging.

Any further comments and objections welcome, but I'd say after like a week this feature will stay merged :P

**Pull request merged**
